# Generated by Django 3.2.13 on 2023-10-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordings',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='recordings',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordings',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video File'),
        ),
        migrations.AlterField(
            model_name='recordings',
            name='name',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.DeleteModel(
            name='VideoRecordings',
        ),
    ]
