# Generated by Django 3.2.13 on 2023-10-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20231001_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordings',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
